version: '3'
services:
  app:
    build: ./app
    container_name: app
    ports:
      - "3000:3000"
    environment:
      - DB_URL=db-app:3001
  db-app:
    build: ./db
    container_name: db-app
    ports:
      - "3001:3001"

networks:
  my-network:
    driver: bridge
